var codeKeyValue = {
  "JSON_FAL" : '参数解析异常',
  "PARAM_ISNULL": '参数不能为空',
  "ORGCODE_NO_EXISTS": 'orgCode不存在',
  "SYS_ERROR": '系统错误',
  "PARAM_ERROR": '参数错误',
  "LOGIN_SID_FAL_0X001": '登录失效，请重新登录',
  "LOGIN_FAL_0x003": '登录失效，请重新登录',
  "LOGIN_FAL_0x004": '登录失效，请重新登录',
  "NO_LOGIN": '您还未登陆',
  "NO_DATA": '没有数据',
  "BUY_COUNT_ERROR": '购买数量不能为0',
  "STOCK_NOENOUGH": '库存不足',
  "PRODUCT_ALREADY_OFFLINE": '提示商品已下架',
  "PRODUCT_ACTIVITY_NO_STARTED": '该商品抢购活动未开始',
  "PRODUCT_ACTIVITY_EXPIRED": '商品抢购活动已失效',
  "SPIKE_STORE_NOTENOUGT_0x001": '秒杀库存不足',
  "ACTIVITY_GET_FAIL_0x001": '未找到活动',
  "PRODID_IS_NULL_0x001": '商品id为空',
  "PROD_S_FAIL_0x001": '商品不存在',
  "SPIKE_U_STORE_FAIL_0x001": '更新秒杀库存失败',
  "SKIPE_U_FAIL_0x001": '更新秒杀活动状态失败',
  "DISCOUNT_U_FAIL_0x001": '限时折扣活动状态更新失败',
  "PROD_STORE_NOTENOUGT_0x001": '商品库存不足',
  "USER_BUY_EXCEED_LIMIT_0x001": '已经超过限购数量',
  "PRODUCT_NOEXIST": '商品信息不存在或已删除',
  "USER_HAS_RESERVE": '已经预约过了哦',
  "USER_COUPON_ALREADY_RECEIVED": '您已经领取过了哦~',
  "COMMON_ADD_FAIL": '领取失败',
  "REDUCED_Q_RECORD_NULL": '满减活动记录不存在',
  "ORDER_NOEXIST": '订单不存在',
  "ORDER_PAYCOMPLETED": '订单已支付',
  "ORDER_ALREADYCANCLE": '订单已取消',
  "VIPUSER_NOEXIST": '没有会员卡信息',
  "RECEIVERINFO_ISNULL": '收货用户信息不能为空',
  "RECEIVERINFO_ISERROR": '收货信息绑定参数不存在',
  "ORGPRICE_ATYPISM": '支付金额与原价不一致',
  "MEMBERPRICE_ATYPISM": '支付金额与会员价不一致',
  "NOALLOW_POINTTYPE": '不允许采用积分的方式付款',
  "POINTPRICE_ATYPISM": '支付金额与积分价不一致',
  "PRODUCT_BUY_COUNT_EXCEED": '限时抢购商品数量超过限购数量',
  "ACTIVITY_STOCK_SHORTAGE": '该充值项已售罄',
  "ACTIVITY_Q_FAL_0X002": '充值发生错误，请联系客服',
  "USERINFO_V_FAL_0X003": '车架号位数不足',
  "REDUCED_Q_PARAM_ERR": '参数为空',
  "PARAM_ERR_0X000": '您的会员卡号不存在',
  'RIGHTS_SERVE_Q_FAIL_0X001':'权益服务未找到记录',
  "RIGHTS_USER_REL_EXSITS":'该用户已领取过该服务',
  "PARAMS_ERROR":'参数错误',
  "LEGAL_INSTRUMENTS_ERROR":'该手机号已提交审核资料',
  "COUPON_ALREADY_EXPIRED":'优惠券已过期',
  "TAKE_SEND_CAR_ERROR":'取送车预约失败',
  "RIGHTS_TAKE_SEND_CAR_S_FAIL_0X001":'保存预约记录异常',
  "RIGHTS_TAKE_SEND_CAR_S_FAIL_0X002":'保存预约记录失败',
  "MISMATCH_DMS_INFO":'车辆信息与DMS不匹配',
  "PUSHAPPLY_S_FAL_0X001": "保存推送失败",
  "PUSHAPPLY_S_FAL_0X002": "保存推送失败",
  "PUSHAPPLY_REL_S_FAL_0X001": "保存推送失败",
  "PUSHAPPLY_REL_S_FAL_0X002": '保存推送失败',
  "NO_OPEN_SERVICE": "没有开通开单权限",
  "MATCH_DATA_FAIL": '无法匹配有效的开通资料',
  "NAME_ISNULL": "姓名不能为空",
  "REQ_PARAM_TYPE_ERROR": "请求操作类型参数错误",
  "PHONE_ISNULL": "手机号不能为空",
  "LICENSEPLATE_FRAMENUMBER_ISNULL": "车牌车架号不能为空",
  "APPOINTED_TIME_ISNULL": "请选择预约时间",
  "COMMON_ORG_ISNULL": "请选择门店",
  "CAR_SERIES_ISNULL": "请选择车系",
  "RECORD_DEALING": "预约信息已在处理中不允许修改",
  "MATCH_DATA_FAIL": "无法匹配有效的开单记录",
  "POSITION_PICTURE_ISNULL": "维修部位和图片都为空",
  "POSITION_PICTURE_NOT_UPLOADED": "玻璃位置和图片有空值",
  "POSITION_PICTURE_INCOMPLETE": "请上传完整维修部位的图片",
  "VISUAL_PICTURE_INCOMPLETE": "视觉类型图片显示不完整"
}

export {
  codeKeyValue
};

